### ISSUE TITLE
Do you consider adding this service to a webpage?

### ISSUE THREAD

**Issue by UltimateJupiter** [vasilescur/WOTO-Time#4]
It would be ideal if you can centralize the request work on one machine, take requests from the webpage and distribute the information via email from that single machine. It is hard for students to keep all their laptops running the code continuously.

And a big THANKYOU

![alt text](http://res.cloudinary.com/sagacity/image/upload/c_crop,h_800,w_616,x_0,y_0/c_scale,w_640/v1419879339/iVegJ35_xfjlfu.gif)

**Comment by vasilescur** [comment]
That's the plan. When I have some time I'll spin up a Google Cloud instance running the code as a server, and sketch out a simple web app allowing users to subscribe to updates.
